---
# Variables for Jenkins Master
jenkins_java_package: "openjdk-21-jdk"
jenkins_repo_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
jenkins_repo_url: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
jenkins_port: 8080
