---
- name: Configure Jenkins Agent
  hosts: slave
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present

    - name: Install Java 17 for project
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Git
      apt:
        name: git
        state: present
    - name: Install Docker
      apt:
        name: maven
        state: present


    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: devopsadmin
        groups: docker
        append: yes
