---
- name: Deploy Banking application
  hosts: kubernetes
  become: false

  tasks:

    - name: Copy Kubernetes deployment file
      copy:
        src: ../bankingdeploy.yaml
        dest: /home/devopsadmin/Banking-Project/bankingdeploy.yaml
        mode: '0644'

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /home/devopsadmin/Banking-Project/bankingdeploy.yaml

    - name: Check deployment rollout
      command: kubectl rollout status deployment/banking-deployment
